name: "Configure app.wsgi file for a deploy"
author: Luke Swanson
description: "Given a set of appropriate inputs, this action prepares the app.wsgi file for an API deploy."
branding:
  icon: 'clipboard'
  color: 'blue'
inputs:
  api_version:
    description: "The version of the API code."
    required: false
    default: 'Testing'
  app_path:
    description: "Local path to the wsgi app being deployed"
    required: true
    default: 'src/app.wsgi'
  config_path:
    description: "Local path to config folder"
    required: false
    default: 'src/config'
runs:
  using: "composite"
  steps:
    - name: Set up src/config
      run: cp ${{ inputs.config_path }}/config.py.template ${{ inputs.config_path }}/config.py 
      shell: bash
    - name: Set API Version
      run: sed -i 's@VERSION_PLACEHOLDER@${{inputs.api_version}}@g' ${{ inputs.config_path }}/config.py
      shell: bash
    - name: Set API Base Path
      run: sed -i 's@placeholder home@${{inputs.api_base}}@g'       ${{ inputs.app_path }}
      shell: bash
