# Workflow to deploy and test Files API to the CI server
name: CI Script - FileAPI
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'push' && github.event.head_commit.message || 'Manual Run') }}
on:
  workflow_dispatch:
  push:
    paths:
    - '.github/workflows/CI_FileAPI.yml'
    - '.github/workflows/DEPLOY_FileAPI.yml'
    - '.github/actions/FileAPI_config/**'
    - 'package/**'
    - 'src/**'
    - 'requirements.txt'

env:
  REPOSITORY: ${{ secrets.DOCKER_IMAGE_REPO }}
  IMAGE:      ${{ github.repository }} # github.repository includes organization as prefix

jobs:
  setup:
    name: Get Branch
    concurrency:
      group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}-setup
      cancel-in-progress: true
    runs-on: ubuntu-22.04
    outputs:
      branch_tag: ${{ steps.step_branch_tag.outputs.branch_tag }}
    steps:
      # Kinda gross string processing to get the shortened version of a branch name.
      # Interpreting the `awk` use:
      #  1. We call split on "/", storing to arr
      #  2. The whole expression calls print on arr's last element:
      #     `split` returns the number of results, so we're indexing at last index (awk uses 1-indexing)
      #  3. Then we pipe to echo, where we construct the output string "branch_tag=<result from awk>"
      - name: Announce step
        run: echo "Splitting " ${{ github.ref_name }}
      - name: Get Branch short name
        id: step_branch_tag
        run: echo "${{ github.ref_name }}" | awk '{ print(arr[split($0, arr, "/")]) }' | echo "branch_tag=$0" >> "$GITHUB_OUTPUT"

  testbed_fileapi_local:
    name: FileAPI Local Testbeds
    uses: ./.github/workflows/TEST_FileAPI_local.yml

  build:
    name: Build Python Package & Image
    needs: [setup, testbed_fileapi_local]
    uses: ./.github/workflows/BUILD_FileAPI.yml
    with:
      image_name:       ${{ github.repository }} # github.repository includes organization as prefix
      image_tag:        ${{ needs.setup.outputs.branch_tag }}
      with_caching: false
    secrets:
      image_repository: ${{ secrets.DOCKER_IMAGE_REPO }}

  deploy:
    name: CI Deploy to GCP
    needs: [build]
    uses: ./.github/workflows/DEPLOY_FileAPI.yml
    with:
      image: ${{ github.repository }}:${{ needs.setup.outputs.branch_tag }}
      remove: false
    secrets: inherit

  testbed_hello_remote:
    name: HelloAPI Remote Testbed
    needs: [deploy]
    uses: ./.github/workflows/TEST_HelloAPI_remote.yml

  testbed_fileapi_remote:
    name: FileAPI Remote Testbeds
    needs: [deploy]
    uses: ./.github/workflows/TEST_FileAPI_remote.yml
