# Workflow to deploy and test Files API to the CI server
name: CI Script - FileAPI
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'push' && github.event.head_commit.message || 'Manual Run') }}
on:
  workflow_dispatch:
  push:
    paths:
    - '.github/workflows/CI_FileAPI.yml'
    - '.github/workflows/DEPLOY_FileAPI.yml'
    - '.github/actions/FileAPI_config/**'
    - 'package/**'
    - 'src/**'
    - 'requirements.txt'

jobs:
  setup:
    name: Get Branch
    runs-on: ubuntu-22.04
    outputs:
      branch-tag: ${{ steps.get-branch.outputs.branch-name }}
    steps:
      - name: Get Branch
        id: get-branch
        uses: opengamedata/actions-get-branch@v1.0

  testbed_fileapi_local:
    name: FileAPI Local Testbeds
    uses: ./.github/workflows/TEST_FileAPI_local.yml

  build:
    name: Build Python Package & Image
    needs: [setup, testbed_fileapi_local]
    uses: ./.github/workflows/BUILD_FileAPI.yml
    with:
      image_name:       ${{ github.repository }} # github.repository includes organization as prefix
      image_tag:        ${{ needs.setup.outputs.branch_tag }}
      with_caching: false
    secrets:
      image_repository: ${{ secrets.DOCKER_IMAGE_REPO }}

  deploy:
    name: CI Deploy to GCP
    needs: [setup, build]
    uses: ./.github/workflows/DEPLOY_FileAPI.yml
    with:
      image_name: ${{ github.repository }} # github.repository includes organization as prefix
      image_tag:  ${{ needs.setup.outputs.branch-tag }}
      remove: false
    secrets: inherit

  testbed_hello_remote:
    name: HelloAPI Remote Testbed
    needs: [setup, deploy]
    uses: ./.github/workflows/TEST_HelloAPI_remote.yml
    with:
      base_url: "${{ needs.setup.outputs.branch-tag }}---${{ github.event.repository.name }}-test-${{ vars.API_FILES_TEST_ID }}.a.run.app"

  testbed_fileapi_remote:
    name: FileAPI Remote Testbeds
    needs: [setup, deploy]
    uses: ./.github/workflows/TEST_FileAPI_remote.yml
    with:
      base_url: "${{ needs.setup.outputs.branch-tag }}---${{ github.event.repository.name }}-test-${{ vars.API_FILES_TEST_ID }}.a.run.app"
