# Workflow to deploy and test Files API to the CI server
name: CI Script - FileAPI
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'push' && github.event.head_commit.message || 'Manual Run') }}
on:
  workflow_dispatch:
  push:
    paths:
    - '.github/workflows/CI_FileAPI.yml'
    - '.github/workflows/DEPLOY_FileAPI.yml'
    - '.github/actions/FileAPI_config/**'
    - 'package/**'
    - 'src/**'
    - 'Dockerfile'
    - 'requirements.txt'

jobs:
  setup:
    name: Get Branch
    runs-on: ubuntu-24.04
    outputs:
      branch_tag: ${{ steps.get-branch.outputs.branch-name }}
    steps:
      - name: Get Branch
        id: get_branch
        uses: opengamedata/actions-get-branch@v1.0
        with:
          n: 14

  testbed_fileapi_local:
    name: FileAPI Local Testbeds
    uses: ./.github/workflows/TEST_FileAPI_local.yml

  package:
    name: Test-Build Python Package
    needs: [setup, testbed_fileapi_local]
    uses: ./.github/workflows/PACKAGE_FileAPI.yml
    with:
      with_caching: false

  build:
    name: Build Docker Image
    needs: [setup, package]
    uses: ./.github/workflows/BUILD_FileAPI.yml
    with:
      image_tag: ${{ needs.setup.outputs.branch_tag }}
    secrets:
      image_repository: ${{ secrets.DOCKER_IMAGE_REPO }}

  deploy:
    name: CI Deploy to GCP
    needs: [setup, build]
    uses: ./.github/workflows/DEPLOY_FileAPI.yml
    with:
      service_name: "ogd-api-files-test"
      image_name: ${{ needs.build.outputs.image_name }}
      revision_tag: "t-${{ needs.setup.outputs.branch_tag }}"
      remove: false
    secrets: inherit

  testbed_hello_remote:
    name: HelloAPI Remote Testbed
    needs: [deploy]
    uses: ./.github/workflows/TEST_HelloAPI_remote.yml
    with:
      base_url: ${{ needs.deploy.outputs.url }}

  testbed_fileapi_remote:
    name: FileAPI Remote Testbeds
    needs: [deploy]
    uses: ./.github/workflows/TEST_FileAPI_remote.yml
    with:
      base_url: ${{ needs.deploy.outputs.url }}
