# Workflow to clean out the directory where a deleted "FileAPI" branch's files were deployed on the CI server
name: Cleanup Dead Branch - FileAPI
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'delete' && github.event.ref || 'Manual Run') }}

on:
  delete: # Trigger automatically when we do a deletion of a branch
  workflow_dispatch:
    
jobs:
  setup:
    name: Get Branch
    runs-on: ubuntu-24.04
    outputs:
      branch_tag: ${{ steps.get_branch_tag.outputs.branch_tag }}
    steps:
      # Kinda gross string processing to get the shortened version of a branch name.
      # Interpreting the `awk` use:
      #  1. We call split on "/", storing to arr
      #  2. The whole expression calls print on arr's last element:
      #     `split` returns the number of results, so we're indexing at last index (awk uses 1-indexing)
      #  3. Then we pipe to echo, where we construct the output string "branch_tag=<result from awk>"
      - name: Announce step
        run: echo "Splitting " ${{ github.ref_name }}
      - name: Get Branch short name
        id: get_branch_tag
        run: |
          BRANCH=$(echo "${{ github.ref_name }}" | awk '{ print(substr(arr[split($0, arr, "/")], 1, 10)) }')
          echo "After split, branch is $BRANCH"
          echo "branch_tag=$BRANCH" >> "$GITHUB_OUTPUT"

  branch_delete:
    name: Dead Branch Cleanup
    if: github.event.ref_type == 'branch'
    needs: [setup]
    uses: ./.github/workflows/DEPLOY_FileAPI.yml
    with:
      image_name: ${{ github.repository }} # github.repository includes organization as prefix
      image_tag:  ${{ needs.setup.outputs.branch_tag }}
      remove: true
      as_latest: false
    secrets: inherit