# Workflow to physically deploy Files API to the CI server
name: Deploy Script - FileAPI
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'push' && github.event.head_commit.message || 'Manual Run') }}
on:
  workflow_call:
    inputs:
      service_name:
        type: string
        description: "The service to which the image should be deployed"
        required: true
      image_name:
        type: string
        description: "The full name of the image, including the tag."
        required: true
      revision_tag:
        type: string
        description: "The name of the revision to use for the deploy. Typically the same as the image tag."
        required: true
      remove:
        type: boolean
        description: "Whether to remove the deploy for the current branch."
        required: true
        default: false
      as_latest:
        type: boolean
        description: "Whether to also deploy/remove as the 'latest' version of API"
        required: false
        default: false
    outputs:
      url:
        description: "The URL of the deploy."
        value: ${{ jobs.derive_url.outputs.url }}

env:
  SERVICE_URL: "file.api.opengamedata.io"
  TEST_URL: ${{ inputs.revision_tag }}---${{ inputs.service_name }}-${{ vars.GCLOUD_REVISION_HASH }}.a.run.app

jobs:
  derive_url:
    name: Derive Target URL for Deploy
    runs-on: ubuntu-24.04
    outputs:
      url: ${{ steps.set-url.outputs.url }}
    steps:
      - name: Release Case
        if: inputs.as_latest == 'true'
        run: echo "DEPLOY_URL=${{ env.SERVICE_URL }}" >> $GITHUB_ENV
      - name: Testing Case
        if: inputs.as_latest != 'true'
        run: echo "DEPLOY_URL=${{ env.TEST_URL }}" >> $GITHUB_ENV
      - name: Check URL
        run: echo "$DEPLOY_URL"
      - name: Get URL
        id: set-url
        run: echo "url=$DEPLOY_URL" >> "$GITHUB_OUTPUT"

  deploy_image:
    name: Deploy Image to Google Cloud
    if: inputs.remove == false
    needs: [derive_url]
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}-deploy
      cancel-in-progress: true
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

    - name: Announce deploy
      run: echo "Deploying ${{ github.ref }} to ${{ needs.derive_url.outputs.url }}"

    # Need checkout in order to have authentication step apply to deploy step.
    - name: Checkout repository
      uses: actions/checkout@v7.0.1
      with:
        fetch-depth: 0

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v3.0.0
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        workload_identity_provider: 'projects/${{ vars.GCLOUD_PROJECT_NUM }}/locations/global/workloadIdentityPools/${{ secrets.GCLOUD_ID_POOL }}/providers/${{ secrets.GCLOUD_ID_PROVIDER }}'
        service_account: ${{ secrets.GCLOUD_DEPLOY_USER }}
    
    - name: Deploy as Latest
      if: ${{ inputs.as_latest == 'true' }}
      uses: 'google-github-actions/deploy-cloudrun@v3.0.1'
      with:
        service: ${{ inputs.service_name }}
        image:   "${{ secrets.DOCKER_IMAGE_REPO }}/${{ inputs.image_name }}"

    - name: Deploy as Test
      if: ${{ inputs.as-latest != 'true' }}
      uses: 'google-github-actions/deploy-cloudrun@v3.0.1'
      with:
        service: ${{ inputs.service_name }}
        image:   "${{ secrets.DOCKER_IMAGE_REPO }}/${{ inputs.image_name }}"
        tag:     ${{ inputs.revision_tag }}
        no_traffic: true

    # 4. Cleanup & complete

  branch_delete:
    name: Remove FileAPI Deploy
    if: inputs.remove == true
    needs: derive_url
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}
      cancel-in-progress: false
    
    steps:

    - name: Announce cleanup
      run: echo "Removing branch deploy at ${{ needs.derive_url.outputs.url }}"
    
    # 1. Remove Image from GitHub

    - name: Remove Image from Repo
      uses: dataaxiom/ghcr-cleanup-action@v1.2.2
      with:
        delete-tags: ${{ inputs.revision-tag }}

    # 2. Remove from GCP
    # TODO

    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v7.0.1
      with:
        path: ./*.log
