# Workflow to physically deploy Files API to the CI server
name: Publish Script - FileAPI
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'push' && github.event.head_commit.message || 'Manual Run') }}
on:
  workflow_call:
    inputs:
      release_type:
        type: string
        description: "The type of release being performed, either 'released' or 'prereleased'."
        required: true

jobs:

  release:
    name: Publish Release to PyPI
    if: inputs.release_type == 'released'
    runs-on: ubuntu-24.04
    environment:
      name: pypi_release
      url: https://pypi.org/manage/project/opengamedata-api-files/
    permissions:
      id-token: write
    steps:

    - name: Download Build Artifact
      id: cached-build
      uses: actions/download-artifact@v7.0.0
      with:
        name: env.CACHE_KEY
        path: ./dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        print-hash: true

  prerelease:
    name: Publish Prerelease to PyPI
    if: inputs.release_type == 'prereleased'
    runs-on: ubuntu-24.04
    environment:
      name: pypi_prerelease
      url: https://pypi.org/manage/project/opengamedata-api-files/
    permissions:
      id-token: write
    steps:

    - name: Download Build Artifact
      id: cached-build
      uses: actions/download-artifact@v7.0.0
      with:
        name: env.CACHE_KEY
        path: ./dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        print-hash: true
        repository-url: https://test.pypi.org/legacy/