# Workflow to deploy and test Files API to the production server
name: Release Script - FileAPI
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'release' && github.ref || 'Manual Run') }}
on:
  #create:
  #  tags:
  #    - '*'
  workflow_dispatch:
  release:
    types: released

jobs:

  build:
    name: Build Python Package
    uses: ./.github/workflows/BUILD_FileAPI.yml
    with:
      with_caching: true

  pypi_release:
    name: Publish Release to PyPI
    needs: [build]
    runs-on: ubuntu-22.04
    environment:
      name: pypi_release
      url: https://pypi.org/manage/project/opengamedata-api-files/
    permissions:
      id-token: write
    steps:

    # 1. Local checkout & config
    - name: Restore Cached Build
      id: cached-build
      uses: actions/cache/restore@v4
      with:
        key: opengamedata-api-files-build-${{ github.run_id }}-${{ github.run_attempt }}
        path: package/dist/
        fail-on-cache-miss: true
    - name: Fail if Cache Restore Failed
      if: steps.cached-build.outputs.cache-hit == 'false'
      run: exit 1
    - name: Pull dist to ./
      run: mv ./package/dist ./dist
      shell: bash
    # 2. Build 

    # 3. Remote config & deploy
    - name: Publish to PyPI
      if: steps.cached-build.outputs.cache-hit == 'true'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        print-hash: true

  wait_for_pypi:
    name: Wait for PyPI to Update
    needs: [build, pypi_release]
    environment: release-wait-deploy # use environment to force waiting a few minutes after the PyPI release.
    runs-on: ubuntu-22.04
    steps:
    - name: Done Waiting
      run: echo "Done waiting."
      shell: bash

  release_deploy:
    name: CI Deploy of Website API
    needs: [build, pypi_release, wait_for_pypi]
    uses: ./.github/workflows/DEPLOY_FileAPI.yml
    with:
      deploy_host: ${{ vars.OGD_SERVICES_HOST }}
    secrets: inherit

  testbed_hello_remote:
    name: HelloAPI Remote Testbed
    needs: release_deploy
    uses: ./.github/workflows/TEST_HelloAPI_remote.yml

  testbed_fileapi:
    name: FileAPI Testbed
    needs: release_deploy
    uses: ./.github/workflows/TEST_FileAPI.yml
