# Workflow to deploy and test Files API to the production server
name: Release Script - FileAPI
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'release' && github.ref || 'Manual Run') }}
on:
  #create:
  #  tags:
  #    - '*'
  workflow_dispatch:
  release:
    types: [released, prereleased]

env:
  CACHE_KEY: opengamedata-api-files-build-${{ github.run_id }}-${{ github.run_attempt }}

jobs:

  testbed_fileapi_local:
    name: FileAPI Local Testbeds
    uses: ./.github/workflows/TEST_FileAPI_local.yml

  package:
    name: Build Python Package
    needs: [testbed_fileapi_local]
    uses: ./.github/workflows/PACKAGE_FileAPI.yml
    with:
      with_caching: true
      cache_to: env.CACHE_KEY

  release:
    name: Publish Release to PyPI
    if: github.event.action == 'released'
    needs: [package]
    runs-on: ubuntu-24.04
    environment:
      name: pypi_release
      url: https://pypi.org/manage/project/opengamedata-api-files/
    permissions:
      id-token: write
    steps:

    - name: Restore Cached Build
      id: cached-build
      uses: actions/download-artifact@v7.0.0
      with:
        name: env.CACHE_KEY
        path: ./dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        print-hash: true

  prerelease:
    name: Publish Prerelease to PyPI
    if: github.event.action == 'prereleased'
    needs: [package]
    runs-on: ubuntu-24.04
    environment:
      name: pypi_prerelease
      url: https://pypi.org/manage/project/opengamedata-api-files/
    permissions:
      id-token: write
    steps:

    - name: Restore Cached Build
      id: cached-build
      uses: actions/download-artifact@v7.0.0
      with:
        name: env.CACHE_KEY
        path: ./dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        print-hash: true
        repository-url: https://test.pypi.org/legacy/

  wait_for_pypi:
    name: Wait for PyPI to Update
    needs: [package, release]
    environment: release-wait-deploy # use environment to force waiting a few minutes after the PyPI release.
    runs-on: ubuntu-24.04
    steps:
    - name: Done Waiting
      run: echo "Done waiting."
      shell: bash

  build:
    name: Build Docker Image for Deploy
    needs: [wait_for_pypi]
    uses: ./.github/workflows/BUILD_FileAPI.yml
    with:
      image_tag:  ${{ github.ref_name }}
    secrets:
      image_repository: ${{ secrets.DOCKER_IMAGE_REPO }}

  # *** Prerelease Case ***

  get_branch:
    name: Get Branch
    if: github.event.action == 'prereleased'
    needs: [build]
    runs-on: ubuntu-24.04
    outputs:
      branch_tag: ${{ steps.get-branch.outputs.branch-name }}
    steps:
    - name: Get Branch
      id: get-branch
      uses: opengamedata/actions-get-branch@v1.1
      with:
        n: 20
        remove: '\.'

  deploy_prerelease:
    name: Release Deploy
    if: github.event.action == 'prereleased'
    needs: [build, get_branch]
    uses: ./.github/workflows/DEPLOY_FileAPI.yml
    with:
      service_name: "ogd-api-files"
      image_name: ${{ needs.build.outputs.image_name }}
      revision_tag: ${{ needs.get_branch.outputs.branch_tag }}
      remove: false
      as_latest: false
    secrets: inherit

  testbed_hello_remote_pre:
    name: HelloAPI Remote Testbed
    needs: [deploy_prerelease]
    uses: ./.github/workflows/TEST_HelloAPI_remote.yml
    with:
      base_url: ${{ needs.deploy_prerelease.outputs.url }}

  testbed_fileapi_pre:
    name: FileAPI Remote Testbed
    needs: [deploy_prerelease]
    uses: ./.github/workflows/TEST_FileAPI_remote.yml
    with:
      base_url: ${{ needs.deploy_prerelease.outputs.url }}

    # *** Release Case ***

  deploy_release:
    name: Release Deploy
    if: github.event.action == 'released'
    needs: [build]
    uses: ./.github/workflows/DEPLOY_FileAPI.yml
    with:
      service_name: "ogd-api-files"
      image_name: ${{ needs.build.outputs.image_name }}
      revision_tag: "latest"
      remove: false
      as_latest: true
    secrets: inherit

  testbed_hello_remote:
    name: HelloAPI Remote Testbed
    needs: [deploy_release]
    uses: ./.github/workflows/TEST_HelloAPI_remote.yml
    with:
      base_url: ${{ needs.deploy_release.outputs.url }}

  testbed_fileapi:
    name: FileAPI Remote Testbed
    needs: [deploy_release]
    uses: ./.github/workflows/TEST_FileAPI_remote.yml
    with:
      base_url: ${{ needs.deploy_release.outputs.url }}
