# Workflow to test the "HelloAPI" portion of Files API on the CI server
name: Remote Testbed - HelloAPI check
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'push' && github.event.head_commit.message || 'Manual Run') }}
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      base_url:
        type: string
        description: "The base URL of the deploy to test."
        required: true
  push:
    branches:
      - "**"
    paths:
    - '.github/workflows/TEST_HelloAPI_remote.yml'
    - '.github/actions/test_config/**'
    - 'tests/cases/apis/HelloAPISuite/**'
    - 'tests/config/**'
    - 'tests/FileAPITestConfig.py'
    - 'requirements.txt'
    - '!.github/workflows/CI_FileAPI.yml'
    - '!.github/actions/**'
    - '!src/**'
    - '!requirements.txt'

env:
  DEFAULT_URL: ${{ github.event.repository.name }}-test-${{ vars.GCLOUD_PROJECT_NUM }}.${{ vars.GCLOUD_REGION }}.run.app
  LOCAL_TEST_DIR: ./tests/cases/apis/HelloAPISuite

jobs:
  check_deploy:
    name: Check for Existing Deploy
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}-hello
      cancel-in-progress: false
    
    steps:

    - name: cURL Check Hello Endpoint
      run: curl -Is --fail-with-body https://${{ case(github.event_name == 'workflow_call', inputs.base_url, env.DEFAULT_URL) }}/hello

  # deploy_if_needed:
  #   name: FileAPI Deploy (If Needed)
  #   needs: check_deploy
  #   if: failure()
  #   uses: ./.github/workflows/DEPLOY_FileAPI.yml
  #   secrets: inherit
  #   with:
  #     deploy_host: ${{ vars.OGD_STAGING_HOST }}
  #     branch: ${{ github.ref_name }}
  #     remove: false

  run_testbed_hello_remote:
    name: Run HelloAPI Remote Testbed
    needs: [check_deploy]
    if: always() && (needs.check_deploy.result == 'success' || needs.deploy_if_needed.result == 'success')
    runs-on: ubuntu-24.04
    container: python:${{ vars.OGD_PYTHON_VERSION }}-alpine
    concurrency:
      group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}-hello
      cancel-in-progress: false
    defaults:
      run:
        shell: sh

    steps:

    - name: Announce testing
      run: echo "Testing HelloAPI endpoint at ${{ case(github.event_name == 'workflow_call', inputs.base_url, env.DEFAULT_URL) }}"

  # 1. Local checkout 
    - name: Checkout repository
      uses: actions/checkout@v7.0.1
      with:
        fetch-depth: 0
    - name: Get Dependencies
      run: python -m pip install -r requirements.txt
    - name: Get current version tag
      id: version-tag
      run: |
        echo "VERSION_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
      # echo "SRC_REVISION=$(git rev-list -1 HEAD -- src/)" >> $GITHUB_OUTPUT
    - name: Set up Config File
      uses: ./.github/actions/test_config
      with:
          endpoint: ${{ case(github.event_name == 'workflow_call', inputs.base_url, env.DEFAULT_URL) }}
          api_version: ${{ steps.version-tag.outputs.VERSION_TAG }}-${{ github.ref_name }}-${{ github.sha }}
          verbose_output: "True"
          shell: sh

  # 2. Build & configure remote environments

  # 3. Perform export
    - name: Execute testbed
      run: python -m unittest discover -s ${{ env.LOCAL_TEST_DIR }}  -p "RemoteCase.py" -t ./

  # 4. Cleanup & complete
    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "test-log"
        path: ./*.log
