# Workflow to build and deploy designer dashboard to server.
name: HelloAPI Testbed
on:
  workflow_dispatch:
  push:
    paths:
    - '.github/workflows/test_webAPI_Hello.yml'
    - '.github/actions/test_config/**'
    - 'tests/**'
    - 'requirements.txt'

env:
  DEPLOY_HOST: ${{ vars.OGD_STAGING_HOST }}
  DEPLOY_DIR:                              ${{ vars.API_BASE_PATH }}/${{ github.event.repository.name }}/${{ github.ref_name }}
  DEPLOY_URL:  ${{ vars.OGD_STAGING_HOST }}/${{ vars.API_BASE_URL }}/${{ github.event.repository.name }}/${{ github.ref_name }}/app.wsgi

jobs:
  run_testbed_hello:
    name: Run HelloAPI Testbed
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.repository }}-CI-${{ github.ref }}
      cancel-in-progress: false

    steps:

  # 1. Local checkout 
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Get Dependencies
      uses: ./.github/actions/install_dependencies
    - name: Set up Config File
      uses: ./.github/actions/test_config
      with:
          endpoint: ${{ env.DEPLOY_URL }}
          verbose_output: "True"

  # 2. Build & configure remote environments

  # 3. Perform export
    - name: Execute testbed
      run: python -m unittest ./tests/cases/t_HelloAPI.py 

  # 4. Cleanup & complete
    - name: Announce test completed
      run: echo "Tested HelloAPI endpoint at ${{ env.DEPLOY_URL }}"
    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v3
      with:
        path: ./*.log
