# Workflow to build and deploy designer dashboard to server.
name: HelloAPI Testbed
on:
  workflow_dispatch:
  push:
    paths:
    - 'tests/**'

env:
  DEPLOY_HOST: ${{ vars.OGD_STAGING_HOST }}
  DEPLOY_DIR:                              ${{ vars.API_BASE_PATH }}/${{ github.event.repository.name }}/${{ github.ref_name }}
  DEPLOY_URL:  ${{ vars.OGD_STAGING_HOST }}/${{ vars.API_BASE_URL }}/${{ github.event.repository.name }}/${{ github.ref_name }}/app.wsgi

jobs:
  run_testbed_hello:
    name: Run HelloAPI Testbed
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:

  # 1. Local checkout 
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Config File
      uses: ./.github/actions/test_config
      with:
          endpoint: ${{ env.DEPLOY_URL }}
          verbose_output: True
    - name: Verify config file
      run: cat tests/config/t_config.py

  # 2. Build & configure remote environments

  # 3. Perform export
    - name: Run Utils testbed
      run: python -m unittest discover -s ./tests/cases/HelloAPI -p "t_*.py" 

  # 4. Cleanup & complete
    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v3
      with:
        path: ./*.log
