# Workflow to build and deploy designer dashboard to server.
name: OGD-Website-API CI Script
on:
  push:
    paths:
    - '.github/workflows/webAPI_CI.yml'
    - '.github/actions/**'
    - 'interfaces/**'
    - 'models/**'
    - 'app.py'
    - 'app.wsgi'
  workflow_dispatch: # Allow manual trigger of this workflow from the Actions tab

env:
  TARGET_PATH:   ${{ vars.WSGI_PATH }}${{ github.event.repository.name }}/${{ github.ref_name }}
  TARGET_HOST: ${{ vars.OGD_STAGING_HOST }}

jobs:
  ci_deploy:
    name: CI Deploy of Website API
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Config File
      uses: ./.github/actions/web_api_config
    #   with:
    #     db_host:
    #     db_user:

    - name: Install OpenConnect
      run: sudo apt-get -q update && sudo apt-get -q install openconnect
    - name: Connect VPN
      run: echo ${{ secrets.VPN_PASS }} | sudo openconnect --protocol=gp -u ${{ secrets.VPN_USER }} --passwd-on-stdin soe.vpn.wisc.edu &

    - name: Setup Access Key
      run: |
        mkdir -p ~/.ssh
        echo '${{ secrets.DEPLOY_KEY }}' >> ./key.txt
        chmod 600 ./key.txt

    - name: Ensure directory exists
      run: ssh -o StrictHostKeyChecking=no -t -i ./key.txt ${{ secrets.DEPLOY_USER }}@${{ env.TARGET_HOST }} "mkdir -p ${{ env.TARGET_PATH }}"

    - name: Upload to web server via rsync
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -vrct --delete --exclude-from 'rsync-exclude'
        path: ./*
        remote_path: ${{ env.TARGET_PATH }}
        remote_host: ${{ env.TARGET_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key:  ${{ secrets.DEPLOY_KEY  }}

    # - name: Restart httpd via ssh
    #   run: ssh -o StrictHostKeyChecking=no -t -i ./key.txt ${{ secrets.DEPLOY_USER }}@${{ vars.OGD_STAGING_HOST }} "sudo /sbin/service httpd restart"
