# Workflow to build and deploy designer dashboard to server.
name: OGD-Website-API Release Script
on:
  #create:
  #  tags:
  #    - '*'
  workflow_dispatch: # Allow manual trigger of this workflow from the Actions tab
  release:
    types: released

env:
  DEPLOY_HOST: ${{ vars.OGD_SERVICES_HOST }}
  DEPLOY_DIR:  ${{ vars.WSGI_PATH }}/${{ github.event.repository.name }}/${{ github.ref_name }}
  DEPLOY_URL:  ${{ vars.OGD_SERVICES_HOST }}/wsgi-bin/${{ github.event.repository.name }}/${{ github.ref_name }}
  URL_PATH:    wsgi-bin/${{ github.event.repository.name }}/${{ github.ref_name }}

jobs:
  production_deploy:
    name: Release Deploy of Website API
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:

  # 1. Local checkout & config
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Config File
      uses: ./.github/actions/web_api_config
      with:
          api_base: ${{ env.DEPLOY_DIR }}

  # 2. Build 

  # 3. Remote config & deploy
    - name: Install OpenConnect
      run: sudo apt-get -q update && sudo apt-get -q install openconnect
    - name: Connect VPN
      run: echo ${{ secrets.VPN_PASS }} | sudo openconnect --protocol=gp -u ${{ secrets.VPN_USER }} --passwd-on-stdin soe.vpn.wisc.edu &

    - name: Setup Access Key
      run: |
        mkdir -p ~/.ssh
        echo '${{ secrets.DEPLOY_KEY }}' >> ./key.txt
        chmod 600 ./key.txt
    - name: Ensure directory exists
      run: ssh -o StrictHostKeyChecking=no -T -i ./key.txt ${{ secrets.DEPLOY_USER }}@${{ env.DEPLOY_HOST }} "mkdir -p ${{ env.DEPLOY_DIR }}"

    - name: Upload to web server via rsync
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -vrc --delete --exclude-from 'rsync-exclude'
        path: ./*
        remote_path: ${{ env.DEPLOY_DIR }}
        remote_host: ${{ env.DEPLOY_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key:  ${{ secrets.DEPLOY_KEY  }}

  # 4. Cleanup & complete
    - name: Restart httpd via ssh
      run: ssh -o StrictHostKeyChecking=no -T -i ./key.txt ${{ secrets.DEPLOY_USER }}@${{ env.DEPLOY_HOST }} "sudo service apache2 restart"

    - name: Announce deploy
      run: echo "Deployed API to ${{ env.DEPLOY_URL }}"
