name: "Configure app.wsgi file for a deploy"
author: Luke Swanson
description: "Given a set of appropriate inputs, this action prepares the app.wsgi file for an API deploy."
branding:
  icon: 'clipboard'
  color: 'blue'
inputs:
  api_version:
    description: "The version of the API code."
    required: false
    default: 'Testing'
  api_base:
    description: "Base path for where the app.wsgi lives."
    required: true
    default: 'path placeholder'
runs:
  using: "composite"
  steps:
    - name: Set up src/config
      run: cp src/config/src/config.py.template src/config/src/config.py 
      shell: bash
    - name: Set API Version
      run: sed -i 's@VERSION_PLACEHOLDER@${{inputs.api_version}}@g' src/config/src/config.py
      shell: bash
    - name: Set API Base Path
      run: sed -i 's@placeholder home@${{inputs.api_base}}@g' app.wsgi
      shell: bash
